### ISSUE TITLE
BEP-44 support?

### ISSUE THREAD

**Issue by p-brz** [jech/dht#24]
Would be nice if the library have support to store arbitrary values,
so other decentralized application could integrate with the Bittorrent DHT more easily.

Have found this was asked before (in issue #9 ).
But, now there is a BEP related (http://bittorrent.org/beps/bep_0044.html).

I think other libraries and programs (like libtorrent) has implemented it.
But i have not found a DHT specific library (in c/c++) with it. 

Thanks

**Comment by amirouche** [comment]
yeah this would be awesome.

**Comment by spikebike** [comment]
I'm all for it, wasn't planning to write it myself.  I'd be willing to help though.  I did the IPv6 port and the pull request was accepted (after some tweaks and improvements).

**Comment by paulobrizolara** [comment]
I wish i could help. But i don't think i have the knowledge (and maybe not the time) yet :/

**Comment by jech** [comment]
Unfortunately BEP-44 is short on rationale, and I don't understand what it is for.  Please reopen if you can explain why you'd want to store arbitrary values in the *BitTorrent* DHT, with all the inefficiency that entails, rather than storing them in the torrent metadata or flooding it across the swarm using an ad-hoc extension to the BitTorrent protocol.

**Comment by naturalpolice** [comment]
Hi @p-brz, if you are still looking for a C implementation of a DHT library with BEP-44 support, I invite you to take a look at the [naturalpolice/libdht](https://github.com/naturalpolice/libdht) project.
